Feature/inventory move
ubis/Freya pull request #4
Opened 2023-08-10 09:17 UTC by artem-alekseev

2023-08-10 09:19 UTC, artem-alekseev commented
I'm just learning GO, please point out my errors, I would like to help you in the project

2023-08-10 13:10 UTC, ubis commented
> I'm just learning GO, please point out my errors, I would like to help you in the project

Hey, thanks for PR! Sure, let me take a look into these changes.

2023-08-11 09:00 UTC, artem-alekseev commented
I added sending notification packages, now you can see equipping and unequipping on characters
I think that this will require improvements, such as pet equipment and others.

I would like something else to help the project, can you tell me what to do next

2023-08-11 12:54 UTC, ubis commented
I guess we should merge this PR first, and to do that, you should look into my comments. And later, perhaps you could look into skills (casting) or quests or NPC's. There is also a problem with astral-gun characters such as ForceShielder/ForceArcher - these are stuck when entered the world, most likely because client tries to cast astral weapon skill.

Now I'm working on a world manager and a proper world cell management and then we will have monsters in a world map.

2023-08-11 13:00 UTC, artem-alekseev commented
I also noticed that the equipment and inventory are not updated when you exit before changing the character, it only works if you exit before choosing a server

2023-08-11 13:03 UTC, ubis commented
This is weird, since DB is actually updated, I would need to check it.

2023-08-11 13:05 UTC, artem-alekseev commented
And I also didn't see any comments on the code, have you already checked it or is it in progress?

I'll try to figure out the activation of astral-gun skills

2023-08-11 13:08 UTC, ubis requested changes

2023-08-11 13:08 UTC, ubis commented on Makefile
> +    		GOOS=windows go build -v -o $(BINDIR)/$(server).exe $(SRVDIR)/$(server);)
I assume you're working on a Windows system, hence you need builds for windows?

You should remove duplicate Make target for this.

We need to detect running OS first, `$(OS)` should be set on Windows, and rest we have Unix & Unix-like OS where `uname` is available.

You can add this after `TARGETS` declaration:

```Make
# detect HOST OS
ifeq ($(OS),Windows_NT)
    HOST_OS := windows
else
    HOST_OS := $(shell uname -s | tr '[:upper:]' '[:lower:]')
endif
```

Then modify `all` and `%` targets to prepend `GOOS=$(HOST_OS)` variable before `go build`:

```Make
all: pre
	$(foreach server,$(TARGETS), \
		GOOS=$(HOST_OS) go build -v -o $(BINDIR)/$(server) $(SRVDIR)/$(server);)
```

Now I'm not sure if you really need to add `*.exe` extension on Windows. I did built Freya with `GOOS=windows` on mac and it produced `*.exe` files.

But then again - I think you're not running in a native Windows environment, because there's no need to pass `GOOS`, as `go` will build for native environment.

2023-08-11 13:08 UTC, ubis commented on cmd/gameserver/packet/const.go
> +	MOVE_ITEM           = 2165
`2165` packet is actually called `StorageExchangeMove`, could you rename it?

Also you should move `NFY_ITEM_EQUIP` & `NFY_ITEM_UNEQUIP` after `DELUSERLIST`, to keep this list in an order.

2023-08-11 13:08 UTC, ubis commented on cmd/gameserver/packet/inventory.go
> +	//log.Debugf("%X", reader.ReadBytes(28))
FYI you can use `network.DumpPacket(reader)` or `network.DumpPacket(writer)` to dump packet content in a table.

Anyway, since these debugs are not used anymore, these can be removed.

2023-08-11 13:08 UTC, ubis commented on cmd/gameserver/packet/inventory.go
> +	packet.WriteByte(0x01)
I assume this byte is status, `1` is success, while `0` for fail.

You want to send this after doing all the movements in the DB, and fail if you have errors in the DB.

2023-08-11 13:08 UTC, ubis commented on cmd/gameserver/packet/inventory.go
> +	if equip > 0 {
I guess if `equip == 1` when player is adding item to inventory or equipment?

And `equip == 0` when player is removing item.

Then probably `inventory` is used to determine from/to where item is being added or removed.

Overall MoveItemMasterServerQuery looks redundant, I don't think we need a separate method for that.

Anyway, this could be refactored by adding `getExhangeMoveType` function:

```Go
func getExhangeMoveType(equip, inventory uint32) string {
	isEquip := equip == 1
	isInventory := inventory == 1

	switch {
	case isEquip && isInventory:
		return rpc.MoveItemEquToEqu
	case isEquip && !isInventory:
		return rpc.MoveItemEquToInv
	case !isEquip && isInventory:
		return rpc.MoveItemInvToEqu
	default:
		return rpc.MoveItemInvToInv
	}
}
```

Then just:

```Go
code := getExhangeMoveType(equip, inventory)
// and everything from MoveItemMasterServerQuery
// also you should add "result" value which will be received on successful DB call
```

2023-08-11 13:08 UTC, ubis commented on cmd/gameserver/packet/inventory.go
> +	if equip > 0 {
Also there is equipment & inventory in character, you can get it from session context:

```Go
ctx, err := parseSessionContext(session)
if err != nil {
	log.Error(err.Error())
	return
}

playerChar := ctx.char
```

You should move items here locally first, before sending updates to the DB.

2023-08-11 13:08 UTC, ubis commented on cmd/masterserver/rpc/inventory.go
> +	var inv = inventory.Inventory{}
These will do nothing, they are nothing, and belong to no one. You can remove these.

Here, you just need to move from inventory to equipment and, of course send an error if even one of query fails.

To not lose data, this should be done in a single query with `START TRANSACTION`:

```SQL
START TRANSACTION;
INSERT INTO characters_equipment ...
DELETE FROM characters_inventory ...
COMMIT;
```

2023-08-11 13:08 UTC, ubis commented on share/rpc/const.go
> +	MoveItemEquToEqu = "MoveItemEquToEqu"
IMO these names should be more understandable.

I assume `MoveItemEquToEqu` is `MoveItemEquipToEquipment`? Perhaps rename it into:
- `AddItemToEquipment`
- `AddItemToInventory`
- `RemoveItemFromEquipment`
- `RemoveItemFromInventory` (though `MoveItemInvToInv` doesn't seem like remove, more like "move from slot to another slot")

2023-08-11 13:08 UTC, ubis commented on share/rpc/const.go
> +	MoveItemEquToEqu = "MoveItemEquToEqu"
So I've did some testing and `MoveItemInvToInv` could be named like `ChangeInventoryItemSlot`, also there is a mistake, it should use `characters_inventory` table:

```Go
func MoveItemInvToInv(c *rpc.Client, r *character.ItemEquipReq, s *character.ItemEquipRes) error {
	var db = g_DatabaseManager.Get(r.Server)

	err := db.MustExec(
			"UPDATE characters_inventory " +
			"SET slot = ? " +
			"WHERE id = ? AND slot = ?",
		r.CreateSlot, r.Id, r.DeleteSlot)
	if err != nil {
		log.Error("[DATABASE]", err)
	}

	return nil
}
```

`MoveItemInvToEqu` is `EquipItem`
`MoveItemEquToInv` is `UnequipItem`

Not sure about `MoveItemEquToEqu`, exchanging equipment weapons sends another packet 2166:

```
2023-08-10 18:58:45.329 [DEBUG] Received Packet `Unknown` (Len: 54, type: 2166, src: 192.168.90.184:56468)
2023-08-10 18:58:45.329 [ERROR] Unknown packet received (Len: 54, type: 2166, src: 192.168.90.184:56468)
2023-08-10 18:58:45.329 [DEBUG] 

      00 01 02 03 04 05 06 07 08 09 0A 0B 0C 0D 0E 0F
-----------------------------------------------------
0000: E2 B7 36 00 00 00 00 00 76 08 01 00 00 00 04 00 
0001: 00 00 01 00 00 00 05 00 00 00 01 00 00 00 05 00 
0002: 00 00 01 00 00 00 04 00 00 00 00 11 38 80 EB FF 
0003: FF FF 00 00 00 00
```

2023-08-11 13:09 UTC, ubis commented
> And I also didn't see any comments on the code, have you already checked it or is it in progress?
> 
> I'll try to figure out the activation of astral-gun skills

Ah yes, sorry. I forgot to end the review :D

2023-08-11 13:17 UTC, ubis commented on Makefile
> +    		GOOS=windows go build -v -o $(BINDIR)/$(server).exe $(SRVDIR)/$(server);)
I've added `*.exe` extension in 1af3907b8044a905969b73706a9f41d0184db192.

Can you check if `GOOS` is set when building on Windows?

2023-08-11 13:20 UTC, artem-alekseev commented
Could you give me access to the repository so I can push to your branches, it's very inconvenient to work through fork

2023-08-11 13:24 UTC, ubis commented
> [artem-alekseev](/artem-alekseev)

Sure, I've sent the invite.

2023-08-11 19:36 UTC, closed without merging